### ISSUE TITLE
Lines break in the middle of words in tables

### ISSUE THREAD

**Issue by rmglennon** [transitland/www-transit-land#159]
In documentation/datastore/api-endpoints.html, some lines in the table are broken in the middle of words. Is there a way to control the wrapping, @hanbyul-here @drewda? Otherwise, the table looks great!

![image](https://cloud.githubusercontent.com/assets/4380498/14189698/7fc7a2ee-f743-11e5-9114-0355dfef9fd7.png)

**Comment by hanbyul-here** [comment]
ah thanks for pointing out. This is solved with f05919e4c54e5aada52093969e41d28a6c85a05b

**Comment by rmglennon** [comment]
Cool. Here's another thing. Also fixed with your change?

documentation/datastore/schedules.html

![image](https://cloud.githubusercontent.com/assets/4380498/14190238/86ee638e-f746-11e5-9285-137dd877f8a6.png)

**Comment by hanbyul-here** [comment]
that commit doesn't fix that problem. On master branch, that column is not wrapped with code block, is this your local thing?

**Comment by hanbyul-here** [comment]
I found more general solution about this problem. this f8c7363f52b55338deb0eab9ee8ec6908115595b should (hopefully) solve that table problem too.

**Comment by rmglennon** [comment]
:100:
